"""adding macaroon model

Revision ID: 01d2f9d4ef7b
Revises: 50c998178d2f
Create Date: 2021-12-09 22:30:38.538822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d2f9d4ef7b'
down_revision = '50c998178d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
