"""update caveat model

Revision ID: 48db1a46b7b9
Revises: 665dd6c34efc
Create Date: 2021-12-07 22:11:23.143894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48db1a46b7b9'
down_revision = '665dd6c34efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
