"""adding macaroon model

Revision ID: 50c998178d2f
Revises: b48d459daeec
Create Date: 2021-12-09 22:19:49.868397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c998178d2f'
down_revision = 'b48d459daeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macaroons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('first_party_caveats_enabled', sa.Boolean(), nullable=False),
    sa.Column('third_party_caveats_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macaroons_id'), 'macaroons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macaroons_id'), table_name='macaroons')
    op.drop_table('macaroons')
    # ### end Alembic commands ###
