"""update caveat model

Revision ID: 665dd6c34efc
Revises: ca7de77bbd2d
Create Date: 2021-12-07 21:59:53.622185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665dd6c34efc'
down_revision = 'ca7de77bbd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
