"""adding macaroon model

Revision ID: b48d459daeec
Revises: f7f9b4e24dba
Create Date: 2021-12-09 22:17:55.592568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48d459daeec'
down_revision = 'f7f9b4e24dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
