"""update caveat model

Revision ID: f7f9b4e24dba
Revises: 48db1a46b7b9
Create Date: 2021-12-07 22:14:37.815887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f9b4e24dba'
down_revision = '48db1a46b7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caveats', sa.Column('location', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caveats', 'location')
    # ### end Alembic commands ###
